"""updates db fields

Revision ID: 047ca99d2cbb
Revises: 429d4394b531
Create Date: 2026-01-08 09:03:51.959078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047ca99d2cbb'
down_revision = '429d4394b531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expertise', sa.String(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('course')

    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.drop_column('expertise')

    # ### end Alembic commands ###
