"""adds fields in mentor

Revision ID: 41fa6ce74059
Revises: 047ca99d2cbb
Create Date: 2026-01-08 19:59:23.400977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41fa6ce74059'
down_revision = '047ca99d2cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
